# Generated by Django 3.2.7 on 2021-09-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='name',
            field=models.CharField(default='NoName', max_length=100),
            preserve_default=False,
        ),
    ]
