# Generated by Django 3.2.7 on 2021-09-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0002_members_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='br_komada',
            field=models.IntegerField(default=0),
        ),
    ]
